# Generated by Django 5.1.2 on 2025-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_address_alter_client_email'),
        ('vehicles', '0004_alter_vehicle_engine_type_alter_vehicle_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('license_plate', 'client'), name='unique_license_plate_per_client'),
        ),
    ]
