# Generated by Django 5.1.2 on 2024-11-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='actual_duration_hours',
            field=models.DurationField(),
        ),
    ]
