# Generated by Django 5.1.2 on 2024-12-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0002_alter_trainingdata_actual_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='actual_duration_hours',
            field=models.DurationField(),
        ),
    ]
