# Generated by Django 5.1.2 on 2025-01-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0003_alter_trainingdata_actual_duration_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
