# Generated by Django 5.1.2 on 2024-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_assigned_mechanics_repairitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairitem',
            name='actual_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairitem',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
