# Generated by Django 5.1.2 on 2024-11-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_estimated_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
