# Generated by Django 5.1.2 on 2024-11-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_total_cost_repairitem_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='branch',
        ),
    ]
