# Generated by Django 5.1.2 on 2025-01-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='cost',
            new_name='cost_part',
        ),
        migrations.AddField(
            model_name='part',
            name='cost_service',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
