# Generated by Django 5.1.2 on 2025-01-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_repairitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Do wykonania'), ('in_progress', 'W trakcie'), ('completed', 'Zakończone'), ('canceled', 'Anulowane')], default='pending', max_length=15),
        ),
    ]
