# Generated by Django 5.0.4 on 2024-05-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nip', models.CharField(blank=True, max_length=50, null=True)),
                ('regon', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='Services', to='visit.clientcar'),
        ),
        migrations.AlterField(
            model_name='service',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='Services', to='visit.client'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mechanics',
            field=models.ManyToManyField(blank=True, related_name='assigned_Services', to='visit.mechanic'),
        ),
        migrations.AddField(
            model_name='service',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='Services', to='visit.company'),
        ),
    ]
