# Generated by Django 5.0.4 on 2024-05-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_rename_service_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='striked_lines',
            field=models.JSONField(default=list),
        ),
    ]
