# Generated by Django 5.0.4 on 2024-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_visit_striked_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='striked_lines',
            field=models.JSONField(default=dict),
        ),
    ]
