# Generated by Django 5.0.4 on 2024-06-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_alter_visit_striked_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='company',
        ),
        migrations.AddField(
            model_name='clientcar',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.company'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='striked_lines',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
