# Generated by Django 5.0.4 on 2024-06-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0007_remove_visit_clients_remove_visit_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcar',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.client'),
        ),
    ]
