# Generated by Django 5.0.4 on 2024-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_alter_clientcar_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcar',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
