# Generated by Django 5.0.4 on 2024-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0009_alter_clientcar_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
