# Generated by Django 5.0.4 on 2024-06-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0010_visit_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekujące'), ('in_progress', 'W trakcie'), ('done', 'Zakończone'), ('archived', 'Zarchiwizowane')], default='pending', max_length=50),
        ),
    ]
