# Generated by Django 5.0.4 on 2024-07-16 15:59

import visit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0013_part_alter_clientcar_license_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='parts',
            field=models.ManyToManyField(blank=True, to='visit.part'),
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', visit.models.CustomIDField(default=visit.models.generate_random_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('parts', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('in_progress', 'W trakcie'), ('done', 'Zakończone'), ('archived', 'Zarchiwizowane')], default='pending', max_length=50)),
                ('striked_lines', models.JSONField(blank=True, default=dict)),
                ('cars', models.ManyToManyField(blank=True, related_name='Estimates', to='visit.clientcar')),
                ('mechanics', models.ManyToManyField(blank=True, related_name='assigned_Estimates', to='visit.mechanic')),
            ],
        ),
    ]
