# Generated by Django 5.1.2 on 2025-03-17 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'W trakcie'), ('completed', 'Zakończone'), ('canceled', 'Anulowane')], default='in_progress', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='appointments.appointment')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='employees.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='clients.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='vehicles.vehicle')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='workshops.workshop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
