# Generated by Django 5.1.2 on 2024-11-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='branch',
        ),
    ]
