# Generated by Django 5.1.2 on 2025-03-17 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Do wykonania'), ('in_progress', 'W trakcie'), ('completed', 'Zakończone'), ('canceled', 'Anulowane')], default='pending', max_length=20)),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='employees.employee')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='service_orders.serviceorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
