# Generated by Django 5.1.2 on 2024-12-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0002_delete_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField()),
                ('smtp_user', models.EmailField(max_length=254)),
                ('smtp_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='workshops.workshop')),
            ],
        ),
    ]
