# Generated by Django 5.1.2 on 2025-03-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_from', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.EmailField(blank=True, default='', max_length=254)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='workshops.workshop')),
            ],
        ),
    ]
