# Generated by Django 5.1.2 on 2024-12-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_user',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
