# Generated by Django 5.1.2 on 2024-12-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0002_alter_emailsettings_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='mail_from',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
