# Generated by Django 5.1.2 on 2024-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.CharField(blank=True, choices=[('A', 'Segment A (VIP)'), ('B', 'Segment B'), ('C', 'Segment C'), ('D', 'Segment D')], max_length=1, null=True),
        ),
    ]
