# Generated by Django 5.1.2 on 2025-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationpart',
            name='buy_cost_part',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationpart',
            name='cost_part',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
