# Generated by Django 5.1.2 on 2025-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationpart',
            name='cost_service',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='QuotationRepairItem',
        ),
    ]
