# Generated by Django 5.1.2 on 2025-03-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_email_workshop_nip_number_workshop_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
